id: P706BC69C
initial_creation_type: input
source_metadata:
  title: Biography Series
  language: fr
  description: 'Translations of various namthar (rnam thar) or biographical and autobiographical
    works:'
  volume:
    8978d1d30c5b4f3099b6518d5fa8025c:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Autobiography
    316a016ef53045428f50f7f2486ee5cb:
      title: A Short Story of the Life and Liberation of Jamyang Khyentse Chökyi Lodrö
      parent: Autobiography
    1292e7cfd0e348738f6fb366e9738824:
      title: 'The Play of Illusion: An Autobiography'
      parent: Autobiography
    7647de3ef7814ded91250347e06ab9f0:
      title: A Brief Autobiographical Sketch
      parent: Autobiography
    3a78072561774a71a2e8e199c64b6ede:
      title: 'The Excellent Path of Devotion: An Abridged Story of a Mendicant’s Experiences
        in Response to Questions from Vajra Kin'
      parent: Autobiography
    5ce01482fbe44ff6aa027819c62a3116:
      title: 'The Quintessence of Marvellous Nectar: A Prayer Based on the Liberational
        Life of the Gentle Protector Guru'
      parent: Biographical Prayer
    676cf7cd5739450f8e42169f86ebacc4:
      title: 'The Hook Which Invokes the Blessings: A Supplication to the Life and
        Liberation of Rigdzin Jalü Dorje'
      parent: Biographical Prayer
    309854977bfd4555a6ae06c972c416b7:
      title: The Seeds of Faith, A Prayer to the Vidyādhara and Great Tertön Lerab
        Lingpa
      parent: Biographical Prayer
    9e7dea52233a4930b0d9e596fb96889d:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Biographical Prayer
    5dd98014e5df406586903c961ed72fc4:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Biographical Prayer
    501e58ab085d41d8a55d7480dbcf22fa:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Biographical Prayer
    b5d99a0c1c79423c9180c8d0c1b1e3a2:
      title: 'The Fresh Utpala: A Prayer to the Great Learned Teacher and Vajra-Holder
        Jamyang Khyenrab Tayé'
      parent: Biographical Prayer
    378187ce348c4d44ba8495ee83633e5a:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Biographical Prayer
    3ed0cb76403a45e9b05c9e50956cc383:
      title: A Prayer Recalling the Life and Liberation of the Great Perfection Adept
        Rangjung Dorje (‘Naturally Arisen Vajra’), Jigme Lingpa
      parent: Biographical Prayer
    379fea1fcfa040e6afe7113173ea447a:
      title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
        Jamyang Khyentse Wangpo
      parent: Biographical Prayer
    9f8e3ae6724d40879546e84daac53f3e:
      title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
      parent: Biographical Prayer
    2bcdb88fc2484b8a909bb9efa8a98b54:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Biographical Prayer
    c599a335d8be4f8989d11eb8806894ce:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Biographical Prayer
    3eb52f2f4de14c8684ee3c2490ab2e46:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Biographical Prayer
    a979cf31675f4fdea43624e126bd4b26:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Biographical Prayer
    ac8a7d8ef994400398c85a2d24224a1b:
      title: 'The Hook of Blessing and Compassion: An Invocation Recalling Briefly
        the Life and Liberation of the Drukchen Drodül Pawo Dorje, My Loving Supreme
        Guru'
      parent: Biography
    b9a5bf85087344f4b3bc1a93e80cd221:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    7cabb214cce8496188fefcb65bc47d27:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    ddca83638fb5466e955539fb41ec1d01:
      title: Biography of Patrul Rinpoche
      parent: Biography
    001f90deac84421c86b7503b0d766137:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    a8bfb169b1c04f96a15a17f3a4c3637e:
      title: Brief Biography of Drakkar Lobzang Palden
      parent: Biography
    661229695fea4861b74b3c8e3b17a5a8:
      title: Brief Biography of Kharlek Tulku Pema Kunzang Rangdrol
      parent: Biography
    1dbe7ded907f4cdab663e7111b43c574:
      title: Brief Biography of Tāranātha
      parent: Biography
    a98fb58fb57a4c4088215e9378b7448f:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    12a2f1421f8a4938bfce2de2b288c97f:
      title: 'Wondrous Light of Lunar Nectar: The Biography of Chatral Kunga Palden,
        a Yogin of the Supreme Vehicle'
      parent: Biography
    954587c834134df2941529ce1a3a3ed0:
      title: In Praise of Sönam Palge
      parent: Biography
    19902d032c6443ed9620805819a7070b:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Biography
    e2716539567f42e9990c4d3e64897c2c:
      title: The Concise Benefits of the Festival of the Tenth Day
      parent: Biography
    4de70407cf27441ba822a89dcade2378:
      title: 'Precise Discernment of Dharmas: A Catalogue of the Complete Collected
        Works of the Omniscient King of Dharma, Rigdzin Jigme Lingpa'
      parent: Biography
    958a4eefb1234628b93cd43d1698f60d:
      title: 'A Bouquet of Uḍumbara Flowers: An Explanation of the Tenth Day'
      parent: Biography
    b7a0281406b4425aa2b5a16aa6a73c22:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    0fb04e8326b94ea988b70a58923703cc:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    b0fbd9f83abf4c0c88e3ee467aad9ee4:
      title: Brief Biography of Gyurme Jamyang Tenpel from Supplementary Biographies
        for the Lineage of the Ḍākinī’s Whispered Transmission of Secret Conduct
      parent: Biography
    a34c6193e7e74c0bba81c2c2831c2aab:
      title: Notes on Chögyal Puntsok Rigdzin and Lhatsün Namkha Jigme’s Incarnations
      parent: Biography
    801d7b7656ea4560a5b41deb67bb5664:
      title: The Life of Khenpo Pema Vajra
      parent: Biography
    ff5e22c77aa944e2bff1189280b3617f:
      title: Biography of Böpa Tulku Dongak Tenpé Nyima
      parent: Biography
    97567b6316db4fc4ac469b220624010c:
      title: 'Light on the Path of Liberation: The Life of the Second Buddha Vasubandhu'
      parent: Biography
    778be8493a1e4844bfbc788ae79a1d6f:
      title: Biography of Dzogchen Khenchen Abu Lhagang
      parent: Biography
    b6c7628b1c784925a0599d236e943951:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: Biography
    3404e8c5918949a6af8d45105247ebea:
      title: The Life of Jamyang Khyentse Chökyi Lodrö
      parent: Biography
    14aa83bde1b14592bdb400b37fe1b44d:
      title: The Life of Jamyang Khyentse Wangpo
      parent: Biography
    575e80c9254d438491f911c796be7a5d:
      title: 'Three Reasons for Confidence: A Work Telling the Life and Liberation
        Story of the Great Master Padmākara'
      parent: Biography
    6459d0974f0348079a98f107b3ff610e:
      title: A Tribute to Tsewang Paljor
      parent: Obituary
created_at: '2022-03-01T03:00:17.844002'
last_modified_at: '2022-03-01T03:00:17.844004'
